name: Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET 9.x
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'
        
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --configuration Release --no-restore
      
    - name: Run tests with detailed output
      run: dotnet test --configuration Release --no-build --logger "trx;LogFileName=test-results.trx" --verbosity detailed
      
    - name: Upload test results
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: Test Results
        path: '**/TestResults/test-results.trx'